# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          newyumi
baseurl:        ""
url:            "https://newyumi.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         newyumi
  url:          https://github.com/newyumi
  email:        queen0701@gmail.com
  github:       newyumi

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/newyumi/newyumi.github.io
